/* WhosOnLogonAccountingServiceSoap12Proxy.h
   Generated by gSOAP 2.7.17 from service.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef WhosOnLogonAccountingServiceSoap12Proxy_H
#define WhosOnLogonAccountingServiceSoap12Proxy_H
#include "WhosOnH.h"

class SOAP_CMAC LogonAccountingServiceSoap12Proxy : public soap
{ public:
	/// Endpoint URL of service 'LogonAccountingServiceSoap12Proxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	LogonAccountingServiceSoap12Proxy();
	/// Constructor with copy of another engine state
	LogonAccountingServiceSoap12Proxy(const struct soap&);
	/// Constructor with engine input+output mode control
	LogonAccountingServiceSoap12Proxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	LogonAccountingServiceSoap12Proxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~LogonAccountingServiceSoap12Proxy();
	/// Initializer used by constructors
	virtual	void LogonAccountingServiceSoap12Proxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'CreateLogonEvent' (returns error code or SOAP_OK)
	virtual	int CreateLogonEvent(_WhosOn__CreateLogonEvent *WhosOn__CreateLogonEvent, _WhosOn__CreateLogonEventResponse *WhosOn__CreateLogonEventResponse);

	/// Web service operation 'CloseLogonEvent' (returns error code or SOAP_OK)
	virtual	int CloseLogonEvent(_WhosOn__CloseLogonEvent *WhosOn__CloseLogonEvent, _WhosOn__CloseLogonEventResponse *WhosOn__CloseLogonEventResponse);

	/// Web service operation 'DeleteLogonEvent' (returns error code or SOAP_OK)
	virtual	int DeleteLogonEvent(_WhosOn__DeleteLogonEvent *WhosOn__DeleteLogonEvent, _WhosOn__DeleteLogonEventResponse *WhosOn__DeleteLogonEventResponse);

	/// Web service operation 'FindLogonEvent' (returns error code or SOAP_OK)
	virtual	int FindLogonEvent(_WhosOn__FindLogonEvent *WhosOn__FindLogonEvent, _WhosOn__FindLogonEventResponse *WhosOn__FindLogonEventResponse);

	/// Web service operation 'FindLogonEvents' (returns error code or SOAP_OK)
	virtual	int FindLogonEvents(_WhosOn__FindLogonEvents *WhosOn__FindLogonEvents, _WhosOn__FindLogonEventsResponse *WhosOn__FindLogonEventsResponse);
};
#endif
