/* WhosOnH.h
   Generated by gSOAP 2.7.17 from service.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef WhosOnH_H
#define WhosOnH_H
#include "WhosOnStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_time
#define SOAP_TYPE_time (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

#define soap_write_time(soap, data) ( soap_begin_send(soap) || soap_put_time(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);

#define soap_read_time(soap, data) ( soap_begin_recv(soap) || !soap_get_time(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);

#ifndef SOAP_TYPE_WhosOn__LogonEventMatch
#define SOAP_TYPE_WhosOn__LogonEventMatch (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_WhosOn__LogonEventMatch(struct soap*, enum WhosOn__LogonEventMatch *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_WhosOn__LogonEventMatch(struct soap*, const char*, int, const enum WhosOn__LogonEventMatch *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_WhosOn__LogonEventMatch2s(struct soap*, enum WhosOn__LogonEventMatch);
SOAP_FMAC3 enum WhosOn__LogonEventMatch * SOAP_FMAC4 soap_in_WhosOn__LogonEventMatch(struct soap*, const char*, enum WhosOn__LogonEventMatch *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2WhosOn__LogonEventMatch(struct soap*, const char*, enum WhosOn__LogonEventMatch *);

#define soap_write_WhosOn__LogonEventMatch(soap, data) ( soap_begin_send(soap) || soap_put_WhosOn__LogonEventMatch(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_WhosOn__LogonEventMatch(struct soap*, const enum WhosOn__LogonEventMatch *, const char*, const char*);

#define soap_read_WhosOn__LogonEventMatch(soap, data) ( soap_begin_recv(soap) || !soap_get_WhosOn__LogonEventMatch(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum WhosOn__LogonEventMatch * SOAP_FMAC4 soap_get_WhosOn__LogonEventMatch(struct soap*, enum WhosOn__LogonEventMatch *, const char*, const char*);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#define soap_write_std__string(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#define soap_new_std__string(soap, n) soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__WhosOn__FindLogonEventsResponse
#define SOAP_TYPE__WhosOn__FindLogonEventsResponse (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__WhosOn__FindLogonEventsResponse(struct soap*, const char*, int, const _WhosOn__FindLogonEventsResponse *, const char*);
SOAP_FMAC3 _WhosOn__FindLogonEventsResponse * SOAP_FMAC4 soap_in__WhosOn__FindLogonEventsResponse(struct soap*, const char*, _WhosOn__FindLogonEventsResponse *, const char*);

#define soap_write__WhosOn__FindLogonEventsResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__WhosOn__FindLogonEventsResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__WhosOn__FindLogonEventsResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__FindLogonEventsResponse * SOAP_FMAC4 soap_get__WhosOn__FindLogonEventsResponse(struct soap*, _WhosOn__FindLogonEventsResponse *, const char*, const char*);

#define soap_new__WhosOn__FindLogonEventsResponse(soap, n) soap_instantiate__WhosOn__FindLogonEventsResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__WhosOn__FindLogonEventsResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _WhosOn__FindLogonEventsResponse * SOAP_FMAC2 soap_instantiate__WhosOn__FindLogonEventsResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__WhosOn__FindLogonEventsResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__WhosOn__FindLogonEvents
#define SOAP_TYPE__WhosOn__FindLogonEvents (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__WhosOn__FindLogonEvents(struct soap*, const char*, int, const _WhosOn__FindLogonEvents *, const char*);
SOAP_FMAC3 _WhosOn__FindLogonEvents * SOAP_FMAC4 soap_in__WhosOn__FindLogonEvents(struct soap*, const char*, _WhosOn__FindLogonEvents *, const char*);

#define soap_write__WhosOn__FindLogonEvents(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__WhosOn__FindLogonEvents(soap, data) ( soap_begin_recv(soap) || !soap_get__WhosOn__FindLogonEvents(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__FindLogonEvents * SOAP_FMAC4 soap_get__WhosOn__FindLogonEvents(struct soap*, _WhosOn__FindLogonEvents *, const char*, const char*);

#define soap_new__WhosOn__FindLogonEvents(soap, n) soap_instantiate__WhosOn__FindLogonEvents(soap, n, NULL, NULL, NULL)


#define soap_delete__WhosOn__FindLogonEvents(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _WhosOn__FindLogonEvents * SOAP_FMAC2 soap_instantiate__WhosOn__FindLogonEvents(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__WhosOn__FindLogonEvents(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__WhosOn__FindLogonEventResponse
#define SOAP_TYPE__WhosOn__FindLogonEventResponse (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__WhosOn__FindLogonEventResponse(struct soap*, const char*, int, const _WhosOn__FindLogonEventResponse *, const char*);
SOAP_FMAC3 _WhosOn__FindLogonEventResponse * SOAP_FMAC4 soap_in__WhosOn__FindLogonEventResponse(struct soap*, const char*, _WhosOn__FindLogonEventResponse *, const char*);

#define soap_write__WhosOn__FindLogonEventResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__WhosOn__FindLogonEventResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__WhosOn__FindLogonEventResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__FindLogonEventResponse * SOAP_FMAC4 soap_get__WhosOn__FindLogonEventResponse(struct soap*, _WhosOn__FindLogonEventResponse *, const char*, const char*);

#define soap_new__WhosOn__FindLogonEventResponse(soap, n) soap_instantiate__WhosOn__FindLogonEventResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__WhosOn__FindLogonEventResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _WhosOn__FindLogonEventResponse * SOAP_FMAC2 soap_instantiate__WhosOn__FindLogonEventResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__WhosOn__FindLogonEventResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__WhosOn__FindLogonEvent
#define SOAP_TYPE__WhosOn__FindLogonEvent (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__WhosOn__FindLogonEvent(struct soap*, const char*, int, const _WhosOn__FindLogonEvent *, const char*);
SOAP_FMAC3 _WhosOn__FindLogonEvent * SOAP_FMAC4 soap_in__WhosOn__FindLogonEvent(struct soap*, const char*, _WhosOn__FindLogonEvent *, const char*);

#define soap_write__WhosOn__FindLogonEvent(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__WhosOn__FindLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get__WhosOn__FindLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__FindLogonEvent * SOAP_FMAC4 soap_get__WhosOn__FindLogonEvent(struct soap*, _WhosOn__FindLogonEvent *, const char*, const char*);

#define soap_new__WhosOn__FindLogonEvent(soap, n) soap_instantiate__WhosOn__FindLogonEvent(soap, n, NULL, NULL, NULL)


#define soap_delete__WhosOn__FindLogonEvent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _WhosOn__FindLogonEvent * SOAP_FMAC2 soap_instantiate__WhosOn__FindLogonEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__WhosOn__FindLogonEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__WhosOn__DeleteLogonEventResponse
#define SOAP_TYPE__WhosOn__DeleteLogonEventResponse (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__WhosOn__DeleteLogonEventResponse(struct soap*, const char*, int, const _WhosOn__DeleteLogonEventResponse *, const char*);
SOAP_FMAC3 _WhosOn__DeleteLogonEventResponse * SOAP_FMAC4 soap_in__WhosOn__DeleteLogonEventResponse(struct soap*, const char*, _WhosOn__DeleteLogonEventResponse *, const char*);

#define soap_write__WhosOn__DeleteLogonEventResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__WhosOn__DeleteLogonEventResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__WhosOn__DeleteLogonEventResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__DeleteLogonEventResponse * SOAP_FMAC4 soap_get__WhosOn__DeleteLogonEventResponse(struct soap*, _WhosOn__DeleteLogonEventResponse *, const char*, const char*);

#define soap_new__WhosOn__DeleteLogonEventResponse(soap, n) soap_instantiate__WhosOn__DeleteLogonEventResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__WhosOn__DeleteLogonEventResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _WhosOn__DeleteLogonEventResponse * SOAP_FMAC2 soap_instantiate__WhosOn__DeleteLogonEventResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__WhosOn__DeleteLogonEventResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__WhosOn__DeleteLogonEvent
#define SOAP_TYPE__WhosOn__DeleteLogonEvent (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__WhosOn__DeleteLogonEvent(struct soap*, const char*, int, const _WhosOn__DeleteLogonEvent *, const char*);
SOAP_FMAC3 _WhosOn__DeleteLogonEvent * SOAP_FMAC4 soap_in__WhosOn__DeleteLogonEvent(struct soap*, const char*, _WhosOn__DeleteLogonEvent *, const char*);

#define soap_write__WhosOn__DeleteLogonEvent(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__WhosOn__DeleteLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get__WhosOn__DeleteLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__DeleteLogonEvent * SOAP_FMAC4 soap_get__WhosOn__DeleteLogonEvent(struct soap*, _WhosOn__DeleteLogonEvent *, const char*, const char*);

#define soap_new__WhosOn__DeleteLogonEvent(soap, n) soap_instantiate__WhosOn__DeleteLogonEvent(soap, n, NULL, NULL, NULL)


#define soap_delete__WhosOn__DeleteLogonEvent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _WhosOn__DeleteLogonEvent * SOAP_FMAC2 soap_instantiate__WhosOn__DeleteLogonEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__WhosOn__DeleteLogonEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__WhosOn__CloseLogonEventResponse
#define SOAP_TYPE__WhosOn__CloseLogonEventResponse (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__WhosOn__CloseLogonEventResponse(struct soap*, const char*, int, const _WhosOn__CloseLogonEventResponse *, const char*);
SOAP_FMAC3 _WhosOn__CloseLogonEventResponse * SOAP_FMAC4 soap_in__WhosOn__CloseLogonEventResponse(struct soap*, const char*, _WhosOn__CloseLogonEventResponse *, const char*);

#define soap_write__WhosOn__CloseLogonEventResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__WhosOn__CloseLogonEventResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__WhosOn__CloseLogonEventResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__CloseLogonEventResponse * SOAP_FMAC4 soap_get__WhosOn__CloseLogonEventResponse(struct soap*, _WhosOn__CloseLogonEventResponse *, const char*, const char*);

#define soap_new__WhosOn__CloseLogonEventResponse(soap, n) soap_instantiate__WhosOn__CloseLogonEventResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__WhosOn__CloseLogonEventResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _WhosOn__CloseLogonEventResponse * SOAP_FMAC2 soap_instantiate__WhosOn__CloseLogonEventResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__WhosOn__CloseLogonEventResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__WhosOn__CloseLogonEvent
#define SOAP_TYPE__WhosOn__CloseLogonEvent (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__WhosOn__CloseLogonEvent(struct soap*, const char*, int, const _WhosOn__CloseLogonEvent *, const char*);
SOAP_FMAC3 _WhosOn__CloseLogonEvent * SOAP_FMAC4 soap_in__WhosOn__CloseLogonEvent(struct soap*, const char*, _WhosOn__CloseLogonEvent *, const char*);

#define soap_write__WhosOn__CloseLogonEvent(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__WhosOn__CloseLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get__WhosOn__CloseLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__CloseLogonEvent * SOAP_FMAC4 soap_get__WhosOn__CloseLogonEvent(struct soap*, _WhosOn__CloseLogonEvent *, const char*, const char*);

#define soap_new__WhosOn__CloseLogonEvent(soap, n) soap_instantiate__WhosOn__CloseLogonEvent(soap, n, NULL, NULL, NULL)


#define soap_delete__WhosOn__CloseLogonEvent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _WhosOn__CloseLogonEvent * SOAP_FMAC2 soap_instantiate__WhosOn__CloseLogonEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__WhosOn__CloseLogonEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__WhosOn__CreateLogonEventResponse
#define SOAP_TYPE__WhosOn__CreateLogonEventResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__WhosOn__CreateLogonEventResponse(struct soap*, const char*, int, const _WhosOn__CreateLogonEventResponse *, const char*);
SOAP_FMAC3 _WhosOn__CreateLogonEventResponse * SOAP_FMAC4 soap_in__WhosOn__CreateLogonEventResponse(struct soap*, const char*, _WhosOn__CreateLogonEventResponse *, const char*);

#define soap_write__WhosOn__CreateLogonEventResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__WhosOn__CreateLogonEventResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__WhosOn__CreateLogonEventResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__CreateLogonEventResponse * SOAP_FMAC4 soap_get__WhosOn__CreateLogonEventResponse(struct soap*, _WhosOn__CreateLogonEventResponse *, const char*, const char*);

#define soap_new__WhosOn__CreateLogonEventResponse(soap, n) soap_instantiate__WhosOn__CreateLogonEventResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__WhosOn__CreateLogonEventResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _WhosOn__CreateLogonEventResponse * SOAP_FMAC2 soap_instantiate__WhosOn__CreateLogonEventResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__WhosOn__CreateLogonEventResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__WhosOn__CreateLogonEvent
#define SOAP_TYPE__WhosOn__CreateLogonEvent (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__WhosOn__CreateLogonEvent(struct soap*, const char*, int, const _WhosOn__CreateLogonEvent *, const char*);
SOAP_FMAC3 _WhosOn__CreateLogonEvent * SOAP_FMAC4 soap_in__WhosOn__CreateLogonEvent(struct soap*, const char*, _WhosOn__CreateLogonEvent *, const char*);

#define soap_write__WhosOn__CreateLogonEvent(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__WhosOn__CreateLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get__WhosOn__CreateLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__CreateLogonEvent * SOAP_FMAC4 soap_get__WhosOn__CreateLogonEvent(struct soap*, _WhosOn__CreateLogonEvent *, const char*, const char*);

#define soap_new__WhosOn__CreateLogonEvent(soap, n) soap_instantiate__WhosOn__CreateLogonEvent(soap, n, NULL, NULL, NULL)


#define soap_delete__WhosOn__CreateLogonEvent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _WhosOn__CreateLogonEvent * SOAP_FMAC2 soap_instantiate__WhosOn__CreateLogonEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__WhosOn__CreateLogonEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WhosOn__ArrayOfLogonEvent
#define SOAP_TYPE_WhosOn__ArrayOfLogonEvent (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_WhosOn__ArrayOfLogonEvent(struct soap*, const char*, int, const WhosOn__ArrayOfLogonEvent *, const char*);
SOAP_FMAC3 WhosOn__ArrayOfLogonEvent * SOAP_FMAC4 soap_in_WhosOn__ArrayOfLogonEvent(struct soap*, const char*, WhosOn__ArrayOfLogonEvent *, const char*);

#define soap_write_WhosOn__ArrayOfLogonEvent(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_WhosOn__ArrayOfLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get_WhosOn__ArrayOfLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 WhosOn__ArrayOfLogonEvent * SOAP_FMAC4 soap_get_WhosOn__ArrayOfLogonEvent(struct soap*, WhosOn__ArrayOfLogonEvent *, const char*, const char*);

#define soap_new_WhosOn__ArrayOfLogonEvent(soap, n) soap_instantiate_WhosOn__ArrayOfLogonEvent(soap, n, NULL, NULL, NULL)


#define soap_delete_WhosOn__ArrayOfLogonEvent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 WhosOn__ArrayOfLogonEvent * SOAP_FMAC2 soap_instantiate_WhosOn__ArrayOfLogonEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_WhosOn__ArrayOfLogonEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_WhosOn__LogonEvent
#define SOAP_TYPE_WhosOn__LogonEvent (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_WhosOn__LogonEvent(struct soap*, const char*, int, const WhosOn__LogonEvent *, const char*);
SOAP_FMAC3 WhosOn__LogonEvent * SOAP_FMAC4 soap_in_WhosOn__LogonEvent(struct soap*, const char*, WhosOn__LogonEvent *, const char*);

#define soap_write_WhosOn__LogonEvent(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_WhosOn__LogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get_WhosOn__LogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 WhosOn__LogonEvent * SOAP_FMAC4 soap_get_WhosOn__LogonEvent(struct soap*, WhosOn__LogonEvent *, const char*, const char*);

#define soap_new_WhosOn__LogonEvent(soap, n) soap_instantiate_WhosOn__LogonEvent(soap, n, NULL, NULL, NULL)


#define soap_delete_WhosOn__LogonEvent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 WhosOn__LogonEvent * SOAP_FMAC2 soap_instantiate_WhosOn__LogonEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_WhosOn__LogonEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns2__FindLogonEvents
#define SOAP_TYPE___ns2__FindLogonEvents (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__FindLogonEvents(struct soap*, struct __ns2__FindLogonEvents *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__FindLogonEvents(struct soap*, const struct __ns2__FindLogonEvents *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__FindLogonEvents(struct soap*, const char*, int, const struct __ns2__FindLogonEvents *, const char*);
SOAP_FMAC3 struct __ns2__FindLogonEvents * SOAP_FMAC4 soap_in___ns2__FindLogonEvents(struct soap*, const char*, struct __ns2__FindLogonEvents *, const char*);

#define soap_write___ns2__FindLogonEvents(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__FindLogonEvents(soap, data), 0) || soap_put___ns2__FindLogonEvents(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__FindLogonEvents(struct soap*, const struct __ns2__FindLogonEvents *, const char*, const char*);

#define soap_read___ns2__FindLogonEvents(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__FindLogonEvents(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns2__FindLogonEvents * SOAP_FMAC4 soap_get___ns2__FindLogonEvents(struct soap*, struct __ns2__FindLogonEvents *, const char*, const char*);

#define soap_new___ns2__FindLogonEvents(soap, n) soap_instantiate___ns2__FindLogonEvents(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__FindLogonEvents(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns2__FindLogonEvents * SOAP_FMAC2 soap_instantiate___ns2__FindLogonEvents(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__FindLogonEvents(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__FindLogonEvent
#define SOAP_TYPE___ns2__FindLogonEvent (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__FindLogonEvent(struct soap*, struct __ns2__FindLogonEvent *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__FindLogonEvent(struct soap*, const struct __ns2__FindLogonEvent *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__FindLogonEvent(struct soap*, const char*, int, const struct __ns2__FindLogonEvent *, const char*);
SOAP_FMAC3 struct __ns2__FindLogonEvent * SOAP_FMAC4 soap_in___ns2__FindLogonEvent(struct soap*, const char*, struct __ns2__FindLogonEvent *, const char*);

#define soap_write___ns2__FindLogonEvent(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__FindLogonEvent(soap, data), 0) || soap_put___ns2__FindLogonEvent(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__FindLogonEvent(struct soap*, const struct __ns2__FindLogonEvent *, const char*, const char*);

#define soap_read___ns2__FindLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__FindLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns2__FindLogonEvent * SOAP_FMAC4 soap_get___ns2__FindLogonEvent(struct soap*, struct __ns2__FindLogonEvent *, const char*, const char*);

#define soap_new___ns2__FindLogonEvent(soap, n) soap_instantiate___ns2__FindLogonEvent(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__FindLogonEvent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns2__FindLogonEvent * SOAP_FMAC2 soap_instantiate___ns2__FindLogonEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__FindLogonEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__DeleteLogonEvent
#define SOAP_TYPE___ns2__DeleteLogonEvent (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__DeleteLogonEvent(struct soap*, struct __ns2__DeleteLogonEvent *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__DeleteLogonEvent(struct soap*, const struct __ns2__DeleteLogonEvent *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__DeleteLogonEvent(struct soap*, const char*, int, const struct __ns2__DeleteLogonEvent *, const char*);
SOAP_FMAC3 struct __ns2__DeleteLogonEvent * SOAP_FMAC4 soap_in___ns2__DeleteLogonEvent(struct soap*, const char*, struct __ns2__DeleteLogonEvent *, const char*);

#define soap_write___ns2__DeleteLogonEvent(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__DeleteLogonEvent(soap, data), 0) || soap_put___ns2__DeleteLogonEvent(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__DeleteLogonEvent(struct soap*, const struct __ns2__DeleteLogonEvent *, const char*, const char*);

#define soap_read___ns2__DeleteLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__DeleteLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns2__DeleteLogonEvent * SOAP_FMAC4 soap_get___ns2__DeleteLogonEvent(struct soap*, struct __ns2__DeleteLogonEvent *, const char*, const char*);

#define soap_new___ns2__DeleteLogonEvent(soap, n) soap_instantiate___ns2__DeleteLogonEvent(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__DeleteLogonEvent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns2__DeleteLogonEvent * SOAP_FMAC2 soap_instantiate___ns2__DeleteLogonEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__DeleteLogonEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__CloseLogonEvent
#define SOAP_TYPE___ns2__CloseLogonEvent (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__CloseLogonEvent(struct soap*, struct __ns2__CloseLogonEvent *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__CloseLogonEvent(struct soap*, const struct __ns2__CloseLogonEvent *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__CloseLogonEvent(struct soap*, const char*, int, const struct __ns2__CloseLogonEvent *, const char*);
SOAP_FMAC3 struct __ns2__CloseLogonEvent * SOAP_FMAC4 soap_in___ns2__CloseLogonEvent(struct soap*, const char*, struct __ns2__CloseLogonEvent *, const char*);

#define soap_write___ns2__CloseLogonEvent(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__CloseLogonEvent(soap, data), 0) || soap_put___ns2__CloseLogonEvent(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__CloseLogonEvent(struct soap*, const struct __ns2__CloseLogonEvent *, const char*, const char*);

#define soap_read___ns2__CloseLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__CloseLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns2__CloseLogonEvent * SOAP_FMAC4 soap_get___ns2__CloseLogonEvent(struct soap*, struct __ns2__CloseLogonEvent *, const char*, const char*);

#define soap_new___ns2__CloseLogonEvent(soap, n) soap_instantiate___ns2__CloseLogonEvent(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__CloseLogonEvent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns2__CloseLogonEvent * SOAP_FMAC2 soap_instantiate___ns2__CloseLogonEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__CloseLogonEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__CreateLogonEvent
#define SOAP_TYPE___ns2__CreateLogonEvent (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__CreateLogonEvent(struct soap*, struct __ns2__CreateLogonEvent *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__CreateLogonEvent(struct soap*, const struct __ns2__CreateLogonEvent *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__CreateLogonEvent(struct soap*, const char*, int, const struct __ns2__CreateLogonEvent *, const char*);
SOAP_FMAC3 struct __ns2__CreateLogonEvent * SOAP_FMAC4 soap_in___ns2__CreateLogonEvent(struct soap*, const char*, struct __ns2__CreateLogonEvent *, const char*);

#define soap_write___ns2__CreateLogonEvent(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__CreateLogonEvent(soap, data), 0) || soap_put___ns2__CreateLogonEvent(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__CreateLogonEvent(struct soap*, const struct __ns2__CreateLogonEvent *, const char*, const char*);

#define soap_read___ns2__CreateLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__CreateLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns2__CreateLogonEvent * SOAP_FMAC4 soap_get___ns2__CreateLogonEvent(struct soap*, struct __ns2__CreateLogonEvent *, const char*, const char*);

#define soap_new___ns2__CreateLogonEvent(soap, n) soap_instantiate___ns2__CreateLogonEvent(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__CreateLogonEvent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns2__CreateLogonEvent * SOAP_FMAC2 soap_instantiate___ns2__CreateLogonEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__CreateLogonEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__FindLogonEvents
#define SOAP_TYPE___ns1__FindLogonEvents (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__FindLogonEvents(struct soap*, struct __ns1__FindLogonEvents *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__FindLogonEvents(struct soap*, const struct __ns1__FindLogonEvents *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__FindLogonEvents(struct soap*, const char*, int, const struct __ns1__FindLogonEvents *, const char*);
SOAP_FMAC3 struct __ns1__FindLogonEvents * SOAP_FMAC4 soap_in___ns1__FindLogonEvents(struct soap*, const char*, struct __ns1__FindLogonEvents *, const char*);

#define soap_write___ns1__FindLogonEvents(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__FindLogonEvents(soap, data), 0) || soap_put___ns1__FindLogonEvents(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__FindLogonEvents(struct soap*, const struct __ns1__FindLogonEvents *, const char*, const char*);

#define soap_read___ns1__FindLogonEvents(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__FindLogonEvents(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns1__FindLogonEvents * SOAP_FMAC4 soap_get___ns1__FindLogonEvents(struct soap*, struct __ns1__FindLogonEvents *, const char*, const char*);

#define soap_new___ns1__FindLogonEvents(soap, n) soap_instantiate___ns1__FindLogonEvents(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__FindLogonEvents(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__FindLogonEvents * SOAP_FMAC2 soap_instantiate___ns1__FindLogonEvents(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__FindLogonEvents(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__FindLogonEvent
#define SOAP_TYPE___ns1__FindLogonEvent (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__FindLogonEvent(struct soap*, struct __ns1__FindLogonEvent *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__FindLogonEvent(struct soap*, const struct __ns1__FindLogonEvent *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__FindLogonEvent(struct soap*, const char*, int, const struct __ns1__FindLogonEvent *, const char*);
SOAP_FMAC3 struct __ns1__FindLogonEvent * SOAP_FMAC4 soap_in___ns1__FindLogonEvent(struct soap*, const char*, struct __ns1__FindLogonEvent *, const char*);

#define soap_write___ns1__FindLogonEvent(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__FindLogonEvent(soap, data), 0) || soap_put___ns1__FindLogonEvent(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__FindLogonEvent(struct soap*, const struct __ns1__FindLogonEvent *, const char*, const char*);

#define soap_read___ns1__FindLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__FindLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns1__FindLogonEvent * SOAP_FMAC4 soap_get___ns1__FindLogonEvent(struct soap*, struct __ns1__FindLogonEvent *, const char*, const char*);

#define soap_new___ns1__FindLogonEvent(soap, n) soap_instantiate___ns1__FindLogonEvent(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__FindLogonEvent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__FindLogonEvent * SOAP_FMAC2 soap_instantiate___ns1__FindLogonEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__FindLogonEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__DeleteLogonEvent
#define SOAP_TYPE___ns1__DeleteLogonEvent (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__DeleteLogonEvent(struct soap*, struct __ns1__DeleteLogonEvent *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__DeleteLogonEvent(struct soap*, const struct __ns1__DeleteLogonEvent *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__DeleteLogonEvent(struct soap*, const char*, int, const struct __ns1__DeleteLogonEvent *, const char*);
SOAP_FMAC3 struct __ns1__DeleteLogonEvent * SOAP_FMAC4 soap_in___ns1__DeleteLogonEvent(struct soap*, const char*, struct __ns1__DeleteLogonEvent *, const char*);

#define soap_write___ns1__DeleteLogonEvent(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__DeleteLogonEvent(soap, data), 0) || soap_put___ns1__DeleteLogonEvent(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__DeleteLogonEvent(struct soap*, const struct __ns1__DeleteLogonEvent *, const char*, const char*);

#define soap_read___ns1__DeleteLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__DeleteLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns1__DeleteLogonEvent * SOAP_FMAC4 soap_get___ns1__DeleteLogonEvent(struct soap*, struct __ns1__DeleteLogonEvent *, const char*, const char*);

#define soap_new___ns1__DeleteLogonEvent(soap, n) soap_instantiate___ns1__DeleteLogonEvent(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__DeleteLogonEvent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__DeleteLogonEvent * SOAP_FMAC2 soap_instantiate___ns1__DeleteLogonEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__DeleteLogonEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__CloseLogonEvent
#define SOAP_TYPE___ns1__CloseLogonEvent (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__CloseLogonEvent(struct soap*, struct __ns1__CloseLogonEvent *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__CloseLogonEvent(struct soap*, const struct __ns1__CloseLogonEvent *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__CloseLogonEvent(struct soap*, const char*, int, const struct __ns1__CloseLogonEvent *, const char*);
SOAP_FMAC3 struct __ns1__CloseLogonEvent * SOAP_FMAC4 soap_in___ns1__CloseLogonEvent(struct soap*, const char*, struct __ns1__CloseLogonEvent *, const char*);

#define soap_write___ns1__CloseLogonEvent(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__CloseLogonEvent(soap, data), 0) || soap_put___ns1__CloseLogonEvent(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__CloseLogonEvent(struct soap*, const struct __ns1__CloseLogonEvent *, const char*, const char*);

#define soap_read___ns1__CloseLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__CloseLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns1__CloseLogonEvent * SOAP_FMAC4 soap_get___ns1__CloseLogonEvent(struct soap*, struct __ns1__CloseLogonEvent *, const char*, const char*);

#define soap_new___ns1__CloseLogonEvent(soap, n) soap_instantiate___ns1__CloseLogonEvent(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__CloseLogonEvent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__CloseLogonEvent * SOAP_FMAC2 soap_instantiate___ns1__CloseLogonEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__CloseLogonEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__CreateLogonEvent
#define SOAP_TYPE___ns1__CreateLogonEvent (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__CreateLogonEvent(struct soap*, struct __ns1__CreateLogonEvent *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__CreateLogonEvent(struct soap*, const struct __ns1__CreateLogonEvent *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__CreateLogonEvent(struct soap*, const char*, int, const struct __ns1__CreateLogonEvent *, const char*);
SOAP_FMAC3 struct __ns1__CreateLogonEvent * SOAP_FMAC4 soap_in___ns1__CreateLogonEvent(struct soap*, const char*, struct __ns1__CreateLogonEvent *, const char*);

#define soap_write___ns1__CreateLogonEvent(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__CreateLogonEvent(soap, data), 0) || soap_put___ns1__CreateLogonEvent(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__CreateLogonEvent(struct soap*, const struct __ns1__CreateLogonEvent *, const char*, const char*);

#define soap_read___ns1__CreateLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__CreateLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns1__CreateLogonEvent * SOAP_FMAC4 soap_get___ns1__CreateLogonEvent(struct soap*, struct __ns1__CreateLogonEvent *, const char*, const char*);

#define soap_new___ns1__CreateLogonEvent(soap, n) soap_instantiate___ns1__CreateLogonEvent(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__CreateLogonEvent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__CreateLogonEvent * SOAP_FMAC2 soap_instantiate___ns1__CreateLogonEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__CreateLogonEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_WhosOn__FindLogonEventsResponse
#define SOAP_TYPE_PointerTo_WhosOn__FindLogonEventsResponse (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_WhosOn__FindLogonEventsResponse(struct soap*, _WhosOn__FindLogonEventsResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_WhosOn__FindLogonEventsResponse(struct soap*, const char *, int, _WhosOn__FindLogonEventsResponse *const*, const char *);
SOAP_FMAC3 _WhosOn__FindLogonEventsResponse ** SOAP_FMAC4 soap_in_PointerTo_WhosOn__FindLogonEventsResponse(struct soap*, const char*, _WhosOn__FindLogonEventsResponse **, const char*);

#define soap_write_PointerTo_WhosOn__FindLogonEventsResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_WhosOn__FindLogonEventsResponse(soap, data), 0) || soap_put_PointerTo_WhosOn__FindLogonEventsResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_WhosOn__FindLogonEventsResponse(struct soap*, _WhosOn__FindLogonEventsResponse *const*, const char*, const char*);

#define soap_read_PointerTo_WhosOn__FindLogonEventsResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_WhosOn__FindLogonEventsResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__FindLogonEventsResponse ** SOAP_FMAC4 soap_get_PointerTo_WhosOn__FindLogonEventsResponse(struct soap*, _WhosOn__FindLogonEventsResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_WhosOn__FindLogonEvents
#define SOAP_TYPE_PointerTo_WhosOn__FindLogonEvents (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_WhosOn__FindLogonEvents(struct soap*, _WhosOn__FindLogonEvents *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_WhosOn__FindLogonEvents(struct soap*, const char *, int, _WhosOn__FindLogonEvents *const*, const char *);
SOAP_FMAC3 _WhosOn__FindLogonEvents ** SOAP_FMAC4 soap_in_PointerTo_WhosOn__FindLogonEvents(struct soap*, const char*, _WhosOn__FindLogonEvents **, const char*);

#define soap_write_PointerTo_WhosOn__FindLogonEvents(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_WhosOn__FindLogonEvents(soap, data), 0) || soap_put_PointerTo_WhosOn__FindLogonEvents(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_WhosOn__FindLogonEvents(struct soap*, _WhosOn__FindLogonEvents *const*, const char*, const char*);

#define soap_read_PointerTo_WhosOn__FindLogonEvents(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_WhosOn__FindLogonEvents(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__FindLogonEvents ** SOAP_FMAC4 soap_get_PointerTo_WhosOn__FindLogonEvents(struct soap*, _WhosOn__FindLogonEvents **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_WhosOn__FindLogonEventResponse
#define SOAP_TYPE_PointerTo_WhosOn__FindLogonEventResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_WhosOn__FindLogonEventResponse(struct soap*, _WhosOn__FindLogonEventResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_WhosOn__FindLogonEventResponse(struct soap*, const char *, int, _WhosOn__FindLogonEventResponse *const*, const char *);
SOAP_FMAC3 _WhosOn__FindLogonEventResponse ** SOAP_FMAC4 soap_in_PointerTo_WhosOn__FindLogonEventResponse(struct soap*, const char*, _WhosOn__FindLogonEventResponse **, const char*);

#define soap_write_PointerTo_WhosOn__FindLogonEventResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_WhosOn__FindLogonEventResponse(soap, data), 0) || soap_put_PointerTo_WhosOn__FindLogonEventResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_WhosOn__FindLogonEventResponse(struct soap*, _WhosOn__FindLogonEventResponse *const*, const char*, const char*);

#define soap_read_PointerTo_WhosOn__FindLogonEventResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_WhosOn__FindLogonEventResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__FindLogonEventResponse ** SOAP_FMAC4 soap_get_PointerTo_WhosOn__FindLogonEventResponse(struct soap*, _WhosOn__FindLogonEventResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_WhosOn__FindLogonEvent
#define SOAP_TYPE_PointerTo_WhosOn__FindLogonEvent (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_WhosOn__FindLogonEvent(struct soap*, _WhosOn__FindLogonEvent *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_WhosOn__FindLogonEvent(struct soap*, const char *, int, _WhosOn__FindLogonEvent *const*, const char *);
SOAP_FMAC3 _WhosOn__FindLogonEvent ** SOAP_FMAC4 soap_in_PointerTo_WhosOn__FindLogonEvent(struct soap*, const char*, _WhosOn__FindLogonEvent **, const char*);

#define soap_write_PointerTo_WhosOn__FindLogonEvent(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_WhosOn__FindLogonEvent(soap, data), 0) || soap_put_PointerTo_WhosOn__FindLogonEvent(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_WhosOn__FindLogonEvent(struct soap*, _WhosOn__FindLogonEvent *const*, const char*, const char*);

#define soap_read_PointerTo_WhosOn__FindLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_WhosOn__FindLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__FindLogonEvent ** SOAP_FMAC4 soap_get_PointerTo_WhosOn__FindLogonEvent(struct soap*, _WhosOn__FindLogonEvent **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_WhosOn__DeleteLogonEventResponse
#define SOAP_TYPE_PointerTo_WhosOn__DeleteLogonEventResponse (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_WhosOn__DeleteLogonEventResponse(struct soap*, _WhosOn__DeleteLogonEventResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_WhosOn__DeleteLogonEventResponse(struct soap*, const char *, int, _WhosOn__DeleteLogonEventResponse *const*, const char *);
SOAP_FMAC3 _WhosOn__DeleteLogonEventResponse ** SOAP_FMAC4 soap_in_PointerTo_WhosOn__DeleteLogonEventResponse(struct soap*, const char*, _WhosOn__DeleteLogonEventResponse **, const char*);

#define soap_write_PointerTo_WhosOn__DeleteLogonEventResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_WhosOn__DeleteLogonEventResponse(soap, data), 0) || soap_put_PointerTo_WhosOn__DeleteLogonEventResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_WhosOn__DeleteLogonEventResponse(struct soap*, _WhosOn__DeleteLogonEventResponse *const*, const char*, const char*);

#define soap_read_PointerTo_WhosOn__DeleteLogonEventResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_WhosOn__DeleteLogonEventResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__DeleteLogonEventResponse ** SOAP_FMAC4 soap_get_PointerTo_WhosOn__DeleteLogonEventResponse(struct soap*, _WhosOn__DeleteLogonEventResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_WhosOn__DeleteLogonEvent
#define SOAP_TYPE_PointerTo_WhosOn__DeleteLogonEvent (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_WhosOn__DeleteLogonEvent(struct soap*, _WhosOn__DeleteLogonEvent *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_WhosOn__DeleteLogonEvent(struct soap*, const char *, int, _WhosOn__DeleteLogonEvent *const*, const char *);
SOAP_FMAC3 _WhosOn__DeleteLogonEvent ** SOAP_FMAC4 soap_in_PointerTo_WhosOn__DeleteLogonEvent(struct soap*, const char*, _WhosOn__DeleteLogonEvent **, const char*);

#define soap_write_PointerTo_WhosOn__DeleteLogonEvent(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_WhosOn__DeleteLogonEvent(soap, data), 0) || soap_put_PointerTo_WhosOn__DeleteLogonEvent(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_WhosOn__DeleteLogonEvent(struct soap*, _WhosOn__DeleteLogonEvent *const*, const char*, const char*);

#define soap_read_PointerTo_WhosOn__DeleteLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_WhosOn__DeleteLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__DeleteLogonEvent ** SOAP_FMAC4 soap_get_PointerTo_WhosOn__DeleteLogonEvent(struct soap*, _WhosOn__DeleteLogonEvent **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_WhosOn__CloseLogonEventResponse
#define SOAP_TYPE_PointerTo_WhosOn__CloseLogonEventResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_WhosOn__CloseLogonEventResponse(struct soap*, _WhosOn__CloseLogonEventResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_WhosOn__CloseLogonEventResponse(struct soap*, const char *, int, _WhosOn__CloseLogonEventResponse *const*, const char *);
SOAP_FMAC3 _WhosOn__CloseLogonEventResponse ** SOAP_FMAC4 soap_in_PointerTo_WhosOn__CloseLogonEventResponse(struct soap*, const char*, _WhosOn__CloseLogonEventResponse **, const char*);

#define soap_write_PointerTo_WhosOn__CloseLogonEventResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_WhosOn__CloseLogonEventResponse(soap, data), 0) || soap_put_PointerTo_WhosOn__CloseLogonEventResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_WhosOn__CloseLogonEventResponse(struct soap*, _WhosOn__CloseLogonEventResponse *const*, const char*, const char*);

#define soap_read_PointerTo_WhosOn__CloseLogonEventResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_WhosOn__CloseLogonEventResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__CloseLogonEventResponse ** SOAP_FMAC4 soap_get_PointerTo_WhosOn__CloseLogonEventResponse(struct soap*, _WhosOn__CloseLogonEventResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_WhosOn__CloseLogonEvent
#define SOAP_TYPE_PointerTo_WhosOn__CloseLogonEvent (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_WhosOn__CloseLogonEvent(struct soap*, _WhosOn__CloseLogonEvent *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_WhosOn__CloseLogonEvent(struct soap*, const char *, int, _WhosOn__CloseLogonEvent *const*, const char *);
SOAP_FMAC3 _WhosOn__CloseLogonEvent ** SOAP_FMAC4 soap_in_PointerTo_WhosOn__CloseLogonEvent(struct soap*, const char*, _WhosOn__CloseLogonEvent **, const char*);

#define soap_write_PointerTo_WhosOn__CloseLogonEvent(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_WhosOn__CloseLogonEvent(soap, data), 0) || soap_put_PointerTo_WhosOn__CloseLogonEvent(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_WhosOn__CloseLogonEvent(struct soap*, _WhosOn__CloseLogonEvent *const*, const char*, const char*);

#define soap_read_PointerTo_WhosOn__CloseLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_WhosOn__CloseLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__CloseLogonEvent ** SOAP_FMAC4 soap_get_PointerTo_WhosOn__CloseLogonEvent(struct soap*, _WhosOn__CloseLogonEvent **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_WhosOn__CreateLogonEventResponse
#define SOAP_TYPE_PointerTo_WhosOn__CreateLogonEventResponse (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_WhosOn__CreateLogonEventResponse(struct soap*, _WhosOn__CreateLogonEventResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_WhosOn__CreateLogonEventResponse(struct soap*, const char *, int, _WhosOn__CreateLogonEventResponse *const*, const char *);
SOAP_FMAC3 _WhosOn__CreateLogonEventResponse ** SOAP_FMAC4 soap_in_PointerTo_WhosOn__CreateLogonEventResponse(struct soap*, const char*, _WhosOn__CreateLogonEventResponse **, const char*);

#define soap_write_PointerTo_WhosOn__CreateLogonEventResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_WhosOn__CreateLogonEventResponse(soap, data), 0) || soap_put_PointerTo_WhosOn__CreateLogonEventResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_WhosOn__CreateLogonEventResponse(struct soap*, _WhosOn__CreateLogonEventResponse *const*, const char*, const char*);

#define soap_read_PointerTo_WhosOn__CreateLogonEventResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_WhosOn__CreateLogonEventResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__CreateLogonEventResponse ** SOAP_FMAC4 soap_get_PointerTo_WhosOn__CreateLogonEventResponse(struct soap*, _WhosOn__CreateLogonEventResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_WhosOn__CreateLogonEvent
#define SOAP_TYPE_PointerTo_WhosOn__CreateLogonEvent (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_WhosOn__CreateLogonEvent(struct soap*, _WhosOn__CreateLogonEvent *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_WhosOn__CreateLogonEvent(struct soap*, const char *, int, _WhosOn__CreateLogonEvent *const*, const char *);
SOAP_FMAC3 _WhosOn__CreateLogonEvent ** SOAP_FMAC4 soap_in_PointerTo_WhosOn__CreateLogonEvent(struct soap*, const char*, _WhosOn__CreateLogonEvent **, const char*);

#define soap_write_PointerTo_WhosOn__CreateLogonEvent(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_WhosOn__CreateLogonEvent(soap, data), 0) || soap_put_PointerTo_WhosOn__CreateLogonEvent(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_WhosOn__CreateLogonEvent(struct soap*, _WhosOn__CreateLogonEvent *const*, const char*, const char*);

#define soap_read_PointerTo_WhosOn__CreateLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_WhosOn__CreateLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _WhosOn__CreateLogonEvent ** SOAP_FMAC4 soap_get_PointerTo_WhosOn__CreateLogonEvent(struct soap*, _WhosOn__CreateLogonEvent **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToWhosOn__ArrayOfLogonEvent
#define SOAP_TYPE_PointerToWhosOn__ArrayOfLogonEvent (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToWhosOn__ArrayOfLogonEvent(struct soap*, WhosOn__ArrayOfLogonEvent *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToWhosOn__ArrayOfLogonEvent(struct soap*, const char *, int, WhosOn__ArrayOfLogonEvent *const*, const char *);
SOAP_FMAC3 WhosOn__ArrayOfLogonEvent ** SOAP_FMAC4 soap_in_PointerToWhosOn__ArrayOfLogonEvent(struct soap*, const char*, WhosOn__ArrayOfLogonEvent **, const char*);

#define soap_write_PointerToWhosOn__ArrayOfLogonEvent(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToWhosOn__ArrayOfLogonEvent(soap, data), 0) || soap_put_PointerToWhosOn__ArrayOfLogonEvent(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToWhosOn__ArrayOfLogonEvent(struct soap*, WhosOn__ArrayOfLogonEvent *const*, const char*, const char*);

#define soap_read_PointerToWhosOn__ArrayOfLogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToWhosOn__ArrayOfLogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 WhosOn__ArrayOfLogonEvent ** SOAP_FMAC4 soap_get_PointerToWhosOn__ArrayOfLogonEvent(struct soap*, WhosOn__ArrayOfLogonEvent **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToWhosOn__LogonEvent
#define SOAP_TYPE_PointerToWhosOn__LogonEvent (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToWhosOn__LogonEvent(struct soap*, WhosOn__LogonEvent *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToWhosOn__LogonEvent(struct soap*, const char *, int, WhosOn__LogonEvent *const*, const char *);
SOAP_FMAC3 WhosOn__LogonEvent ** SOAP_FMAC4 soap_in_PointerToWhosOn__LogonEvent(struct soap*, const char*, WhosOn__LogonEvent **, const char*);

#define soap_write_PointerToWhosOn__LogonEvent(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToWhosOn__LogonEvent(soap, data), 0) || soap_put_PointerToWhosOn__LogonEvent(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToWhosOn__LogonEvent(struct soap*, WhosOn__LogonEvent *const*, const char*, const char*);

#define soap_read_PointerToWhosOn__LogonEvent(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToWhosOn__LogonEvent(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 WhosOn__LogonEvent ** SOAP_FMAC4 soap_get_PointerToWhosOn__LogonEvent(struct soap*, WhosOn__LogonEvent **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#define soap_write_PointerTostd__string(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTostd__string(soap, data), 0) || soap_put_PointerTostd__string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);

#define soap_read_PointerTostd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostd__string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerToWhosOn__LogonEvent
#define SOAP_TYPE_std__vectorTemplateOfPointerToWhosOn__LogonEvent (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerToWhosOn__LogonEvent(struct soap*, std::vector<WhosOn__LogonEvent * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerToWhosOn__LogonEvent(struct soap*, const std::vector<WhosOn__LogonEvent * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerToWhosOn__LogonEvent(struct soap*, const char*, int, const std::vector<WhosOn__LogonEvent * >*, const char*);
SOAP_FMAC3 std::vector<WhosOn__LogonEvent * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerToWhosOn__LogonEvent(struct soap*, const char*, std::vector<WhosOn__LogonEvent * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerToWhosOn__LogonEvent(soap, n) soap_instantiate_std__vectorTemplateOfPointerToWhosOn__LogonEvent(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerToWhosOn__LogonEvent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::vector<WhosOn__LogonEvent * > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfPointerToWhosOn__LogonEvent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerToWhosOn__LogonEvent(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of WhosOnH.h */
