#!/bin/bash
# 
# Wrapper for the whoson logon/logoff event handler command. Use whosonp to
# integrate this script with loginwindow.
#
# Author: Anders Lövgren
# Date:   2012-03-22
#

WHOSON_GLOB_PREF="/etc/whoson.conf"
WHOSON_USER_PREF="~/.whoson.conf"

# If program is not in PATH:
# WHOSON_PROGRAM=/opt/whoson/bin/whoson

if [ -e ${WHOSON_USER_PREF} ]; then
  . ${WHOSON_USER_PREF}
fi
if [ -e ${WHOSON_GLOB_PREF} ]; then
  . ${WHOSON_GLOB_PREF}
fi
if [ -z "${WHOSON_SOAP_ENDPOINT}" ]; then
  export WHOSON_SOAP_ENDPOINT="http://server.example.com/whoson/"
fi

if [ "${WHOSON_DEBUG}" != "0" ]; then
  set -x
fi
if [ -z "${WHOSON_PROGRAM}" ]; then
  WHOSON_PROGRAM=$(which whoson)
fi

if ! [ -x ${WHOSON_PROGRAM} ]; then
  echo "$0: can't find whoson"
  exit 1
fi

${WHOSON_PROGRAM} $*
